### ISSUE TITLE
Redis in production

### ISSUE THREAD

**Issue by ixartz** [jacob-ebey/remix-ecommerce#1]
If I'm not mistaken: after reading the article on Remix.run website, the example is deployed on fly.io?
I see you are using Redis and you use docker-composer for Redis in local environment.

But for production environment, which Redis instance you use? The Redis instance isn't hosted on fly.io?

**Comment by jacob-ebey** [comment]
The Redis instance is hosted on fly.io. There are like 5 regions or so the app is running in, each region has 2 app instances each with their own persistent volume. There is then a separate fly.io app that is running the Redis instance with its own volume. There is 1 Redis instance in each region the app is running. Using internal addresses for connecting to Redis from the application allows it to connect to whatever Redis instance is closest to the app (probably in the same building).

You can read about how to deploy a Redis instance to fly here: https://fly.io/docs/reference/redis/

From what I've heard the awesome folks over there are working on making it even easier to use Redis on their platform.

**Comment by ixartz** [comment]
@jacob-ebey Thank you for taking the time to share your insight about Redis. Now, I understand a little bit more about it.

Hope they make things even easier with Redis with fly.io ;) Couldn't wait.
